CREATE TABLE items (
-- two dashes makes a comment
-- column name
--           column data type
--                        extra column details
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  item_name    TEXT         NOT NULL,
  description  TEXT,
  completed    BOOLEAN      DEFAULT false,  
  created TIMESTAMPTZ NOT NULL DEFAULT now()
);

	
DROP TABLE items;

DROP TABLE IF EXISTS items;

INSERT INTO items (item_name, description) VALUES ('bread', 'multigrain');
INSERT INTO items (item_name, description) VALUES ('butter', 'salted');
insert into items (item_name, description) values ('tea', 'not caffeinated');

INSERT INTO items 
  (item_name, description)
VALUES 
  ('Avocados', 'avacado mash'),
  ('Orange juice', 'not just for breakfast'),
  ('Ice Cream', 'Ben & Jerry''s'),
  ('Oil Change', 'stop at dealership'),
  ('Cat Food', null),
  ('Sun Glasses', 'for vacation'),
  ('Dark roast', 'nectar of the gods'),
  ('Running Shoes', null),
  ('Espresso', 'nectar of the gods'),
  ('Merlot', 'for dinner');

 
SELECT * FROM items;
SELECT id, completed FROM items;
SELECT * FROM items WHERE id = 5;
SELECT item_name FROM items WHERE id = 5;

UPDATE items SET description = 'tasty for cats, not for humans' WHERE id = 8;

DELETE FROM items WHERE item_name = 'Orange juice';
DELETE FROM items WHERE id > 25;

-- fun with selects
SELECT * FROM items ORDER BY item_name DESC;
SELECT * FROM items LIMIT 3;

-- now we have created the products table
SELECT COUNT(*) FROM products;
SELECT * FROM products LIMIT 10;
SELECT * FROM products WHERE aisle = 'coffee';
SELECT COUNT(*) FROM products WHERE aisle = 'coffee';

-- names of all the aisles
SELECT DISTINCT aisle FROM products ORDER BY aisle;
SELECT COUNT(DISTINCT aisle) FROM products;

SELECT * FROM products WHERE aisle = 'tea' AND price > 40;
SELECT product_name 
  FROM products 
  WHERE aisle = 'tea' 
  ORDER BY price DESC 
  LIMIT 1;
 
 -- find all teas with herbal in the name
SELECT product_name FROM products WHERE product_name ILIKE '%hErBaL%' AND aisle = 'tea';

SELECT * FROM products WHERE department = 'pets' ORDER BY price DESC;

SELECT department, COUNT(*) FROM products GROUP BY department;

SELECT * FROM products WHERE product_name ILIKE '%canned%' OR product_name ILIKE '%tea%';

SELECT department, ROUND(AVG(price), 2) FROM products GROUP BY department ORDER BY AVG(price);


